### ISSUE TITLE
(B)[UI BRANCH] Addition of selections (FIXED)

### ISSUE THREAD

**Issue by dafral** [TinoTano/AoE_Project2#10]
When you select an unit and then you select a group of units with the selection square, instead of de-selecting the first unit or group unit, it adds all the units and all of them are selected.

**Comment by rodrigodpl** [comment]
Should work like this. Maybe AoE does that, but i consider it unuseful. If there are questions regarding this please discuss with me.

**Comment by dafral** [comment]
If it's a game dessign election, then FIXED 👍
