### ISSUE TITLE
(B)[UI BRANCH] Units can be selected more than one time

### ISSUE THREAD

**Issue by dafral** [TinoTano/AoE_Project2#11]
When you select a group of units and you reselect them, in the UI it shows like there are the double of troops that are selected. You can do this infinite times with the same group of troops.

**Comment by JosepContact** [comment]
Fixed, please review.

**Comment by dafral** [comment]
Reviewed, and it stills doesn't work :(

**Comment by rodrigodpl** [comment]
This should be fixed when merging with pathfinding branch (already in master)
Selection has been reworked.
