### ISSUE TITLE
(A)[PATHFINDING] dll corruption (FIXED)

### ISSUE THREAD

**Issue by dafral** [TinoTano/AoE_Project2#18]
After playing for a while, a breakpoint happens and if you continue with the executation, a dll gets corrupted and it creates another breakpoint.
![0ebc46568c784ab54a236127190a5d82 1](https://cloud.githubusercontent.com/assets/17141027/24578413/617a1afc-16e0-11e7-86d9-8a4fe6690ba9.png)

You can continue after this, but almost all the sprites disappear from the game.

**Comment by rodrigodpl** [comment]
Fixed, please review

**Comment by dafral** [comment]
FIXED & REVIEWED 👍
