### ISSUE TITLE
(B)[UI] You can't see units stats after selecting the building (FIXED)

### ISSUE THREAD

**Issue by dafral** [TinoTano/AoE_Project2#21]
When you select the building, its stats are displayed in the UI. If you select units after that, their stats are not displayed in the UI, instead the building stats are still being showed.

![6d1c137824861e8c7e612e0462db7da0](https://cloud.githubusercontent.com/assets/17141027/24578613/0323fb68-16e4-11e7-8af9-7fe1f6899033.png)
Here the units are selected but you can't see their stats.

**Comment by JosepContact** [comment]
Also fixed

**Comment by dafral** [comment]
FIXED & REVIEWED 👍
