### ISSUE TITLE
(A)[UI] UI goes crazy after game loops (+info in description)(FIXED)

### ISSUE THREAD

**Issue by dafral** [TinoTano/AoE_Project2#22]
When you go back to the menu and back to the game again, UI has a lot of problems. Some examples that happen when you do this:

- **UI Elements recolocation**: The position of this element is not the correct one.
![a505810c1d4558eae7dc637d239d7efc](https://cloud.githubusercontent.com/assets/17141027/24578659/0f8bd780-16e5-11e7-92a9-7e0d76639291.png)

- **UI Elements disappearing**: Here all the UI has disappeared.
![0197061b534c2f2da9b4fa7ed0811718](https://cloud.githubusercontent.com/assets/17141027/24578682/8f333da2-16e5-11e7-86c0-354a6cb7fd47.png)

- **Building losing life**: The life bar of the building has some red in it when nobody has attacked it. Here we also can see that some elements are missing (options button) or some elements are not in the correct position (building stats).
![17d9f2d10b6fdfac8987b68abd670375](https://cloud.githubusercontent.com/assets/17141027/24578675/762c8b7e-16e5-11e7-8888-5b855eafb492.png)

- **Crash**: Sometimes it crashes after loops.
![ff4e42ece2ffeca52be2f9321e1e447d 1](https://cloud.githubusercontent.com/assets/17141027/24578700/eb50fdc2-16e5-11e7-8e2f-8355f6c23813.png)

**Comment by JosepContact** [comment]
ALL FIXED

**Comment by dafral** [comment]
There are still some problems with the UI, but it doesn't look like they have anything to do with the menu loop. So, FIXED & REVIEWED 👍
