### ISSUE TITLE
(A)[MASTER] HUD Crash (FIXED)

### ISSUE THREAD

**Issue by dafral** [TinoTano/AoE_Project2#33]
There is a crash in the HUD (Division by 0)
![fc50d16f554f3eae69eb85e2c4b0797e](https://cloud.githubusercontent.com/assets/17141027/24668071/e0ba030e-1965-11e7-8c7a-6b7cc4ecdc6d.png)

**Comment by JosepContact** [comment]
Fixed. But would be interesting to keep an eye on max_life from the entity unit

**Comment by dafral** [comment]
FIXED & REVIEWED 👍
