### ISSUE TITLE
(B)[MASTER] Negative life in buildings (FIXED)

### ISSUE THREAD

**Issue by dafral** [TinoTano/AoE_Project2#36]
Sometimes when the building is destroyed, the life goes negative.
![51d72300-16dc-409f-8815-faea0dacbbb0](https://cloud.githubusercontent.com/assets/17141027/24669557/3324d1be-196b-11e7-8f65-7c6c415d3d5f.jpg)

**Comment by JosepContact** [comment]
Oh no baby what is you doing

**Comment by dafral** [comment]
FIXED & REVIEWED 👍
