### ISSUE TITLE
(C)[MASTER] TOWN_CENTER

### ISSUE THREAD

**Issue by dafral** [TinoTano/AoE_Project2#37]
😡 😡 😡 😡 😡  It should be TOWN CENTER 😡 😡 😡 😡 😡
![51d72300-16dc-409f-8815-faea0dacbbb0](https://cloud.githubusercontent.com/assets/17141027/24669646/787d2ca2-196b-11e7-9a8e-f7447425147b.jpg)

**Comment by JosepContact** [comment]
pls don't fire me
