### ISSUE TITLE
[B] Enemies are allied units + Enemy life bars

### ISSUE THREAD

**Issue by IVREI0T** [TinoTano/AoE_Project2#61]
![image](https://cloud.githubusercontent.com/assets/17142213/25848188/7ab7d008-34b9-11e7-9fed-e2e206b34a8b.png)
Just got in the game, I don't understand what's going on and for some reason I have started killing people with a green bar. Are they my friends? If they're my enemies, why do they have a green health bar?

**Comment by dafral** [comment]
Enemies can be moved, and maked them fight against each other. 

However, we should consider changing the color of the enemy life bars.
