### ISSUE TITLE
Ranged units don't attack properly 

### ISSUE THREAD

**Issue by dafral** [TinoTano/AoE_Project2#89]
**Issue type**: 
Issue type B: The game doesn't work like intended (Broken controls, broken rules...)

**What has happened?**:
Ranged units only attack when they feel like.

**What should has happened**:
Ranged units should always attack the way it's intended.

**Steps to reproduce issue**:
Attack with a ranged unit.

**Build version**:
0.91

**Comment by JosepContact** [comment]
Could work better but won't make the cut
