### ISSUE TITLE
Minimap camera doesn't show what you are seeing

### ISSUE THREAD

**Issue by dafral** [TinoTano/AoE_Project2#93]
**Issue type**: 
Issue type B: The game doesn't work like intended (Broken controls, broken rules...)

**What has happened?**:
Minimap camera is moved.

**What should has happened**:
Minimap camera shows you what you are seeing in the screen.

**Steps to reproduce issue**:
Click the minimap one time, and it moves.

**Build version**:
0.91

**Comment by JosepContact** [comment]
Tested and working
