### ISSUE TITLE
Crash when gathering rocks

### ISSUE THREAD

**Issue by dafral** [TinoTano/AoE_Project2#95]
**Issue type**: 
Issue type A: The game is not playable (Game crashing bugs, build not working...)

**What has happened?**:
The game crashes when you try to gather rocks.

**What should has happened**:
The game doesn't crash.

**Steps to reproduce issue**:
Try to gather rock.

**Build version**:
0.91

**Comment by JosepContact** [comment]
The crash is no longer there. But the rocks are ungatherable.
